# Generated by Django 3.2.5 on 2023-09-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(null=True)),
                ('cover_url', models.URLField(null=True)),
                ('file', models.FileField(null=True, upload_to='file', verbose_name='上传文件')),
            ],
        ),
    ]
